services:
  database:
    image: nouchka/sqlite3
    restart: unless-stopped
    volumes:
      - ./data/sqlite:/data

  directus:
    restart: unless-stopped
    image: directus/directus:9.23.1
    environment:
      DB_CLIENT: 'sqlite3'
      DB_HOST: 'database'
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEY: ${DIRECTUS_KEY}
      SECRET: ${DIRECTUS_SECRET}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL}
      STORAGE_LOCAL_ROOT: '/directus/uploads'
      GENERATE_SOURCEMAP: 'false'
      EXTENSIONS_PATH: './extensions'
    ports:
      - 18055:8055
    depends_on:
      - database
    networks:
      - directus-network

networks:
  directus-network:
    driver: bridge
    name: directus-endereco-br-network
